name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
        - uses: octokit/request-action@v2.x
          id: create_issue
          with:
            route: POST /repos/{owner}/{repo}/issues
            owner: al3xparker
            repo: training-gha
            name: "Create a new issue"
            head_sha: ${{ github.sha }}
            output: |
              title: Found a bug
              summary: I'm having a problem with this.
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}