name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
        - name: execute curl
          run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/al3xparker/training-gha/issues \
            -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'